import Head from "next/head";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();

  function handleSubmit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const data = new FormData(event.currentTarget);

    if (!data.get("name")) {
      return;
    }

    router.push(`/game/${data.get("name")}`);
  }

  return (
    <>
      <Head>
        <title>Minesweeper</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center items-center h-screen">
        <form onSubmit={handleSubmit} className="flex flex-col gap-2">
          <label className="text-lg font-bold" htmlFor="name">
            Nom
          </label>
          <input
            type="text"
            id="name"
            name="name"
            placeholder="Alexandre"
            required
            className="border px-3 py-1 rounded"
          />
          <button
            className="bg-green-500 text-white px-3 py-2 hover:bg-green-600 rounded"
            type="submit"
          >
            Join
          </button>
        </form>
      </main>
    </>
  );
}

